### ISSUE TITLE
New 보드시 빈공간 나옴 

### ISSUE THREAD

**Issue by andrew-kim-machbase** [machbase/neo-web#36]
2023/04/27 12:11:48.613 WARN  http-log          404 |      18.122µs |       127.0.0.1 |      0 B |      0 B | HTTP/1.1 GET     127.0.0.1:5654/web/ui/tag-view/assets/index.b7169c12.css

Linux/chrome/0.9.9.11

**Comment by briggssong** [comment]
https://github.com/machbase/neo-web/pull/37 에서 수정완료 하였습니다.
